name: 'resend-action'
description: 'Sends an email using Resend. See full API spec at: https://resend.com/docs/api-reference/emails/send-email'
inputs:
  api-key:
    description: 'Resend API Key. Keep this in a Secret.'
    required: true
  from-domain:
    description: 'Domain of the sender. This must be verified with Resend. Ex: github.com'
    required: true
  sender:
    description: 'Resend API Key. Keep this in a Secret.'
    required: true
    default: 'no-reply'
  subject:
    description: 'Subject of the email.'
    required: true
    default: 'Notice'
  to-array:
    description: 'Who to send the email to, at least one is required but multiple separated by commas can be provided.'
    required: true
  send-to-separately:
    description: 'If set to true then emails in the to array will each receive a separate email. BCC and CC are ignored in this case'
    required: false
    default: 'false'
  delay:
    description: 'When using send-to-separately several emails will be sent. This can quickly hit the Resend rate limit. This delay in milliseconds will be enforced between emails.'
    required: false
    default: '1000'
  reply-to-array:
    description: 'Comma separated reply-to list.'
    required: false
  bcc-array:
    description: 'Comma separated bcc list.'
    required: false
  cc-array:
    description: 'Comma separated cc list.'
    required: false
  scheduled-at:
    description: 'Schedule the email at a later time using iso8601 or natural language.'
    required: false
  dry-run:
    description: 'If set to true the API call will not be made only logging will occur.'
    required: false
  text:
    description: 'Text to send. Only include this or html, not both.'
    required: false
  html:
    description: 'HTML to send. Only include this or text, not both.'
    required: false
runs:
  using: 'node20'
  main: 'dist/index.js'
